version: '3'
services:
  odoo:
    build: .
    ports:
      - "8069:8069"
    environment:
      - HOST=0.0.0.0
    depends_on:
      - db
      
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
